import = [
    "~/.config/alacritty/themes/themes/citylights.toml"
]

[window]
blur=true
opacity=1
decorations="None"

[env]
TERM="xterm-256color"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"
